[platformio]

; === QUICK SWITCH ===
; Firmware principal:
;   pio run -e tracker -t upload
;   pio device monitor -e tracker
; Utilidad módem (AT passthrough):
;   pio run -e at_passthrough -t upload
;   pio device monitor -e at_passthrough
; Atajo mental: tracker = firmware real / at_passthrough = diagnóstico módem

default_envs = tracker

; ====== Firmware principal (tracker) ======
[env:tracker]
platform = espressif32
board = esp32s3usbotg
framework = arduino

monitor_speed = 115200
upload_port = COM8

build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1

; ====== Utilidad: AT Passthrough (módem) ======
[env:at_passthrough]
platform = espressif32
board = esp32s3usbotg
framework = arduino

monitor_speed = 115200
upload_port = COM8

build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1

; Este env compila desde esta carpeta en vez de /src
src_dir = tools/at_passthrough/src