[platformio]
default_envs = tracker

[env]
platform = espressif32
board = esp32s3usbotg
framework = arduino
monitor_speed = 115200
upload_port = COM5
build_flags =
 -D ARDUINO_USB_CDC_ON_BOOT=1
 -D ARDUINO_USB_MODE=1
lib_deps =
 https://github.com/lewisxhe/TinyGSM-fork.git
 vshymanskyy/StreamDebugger@^1.0.1
 knolleary/PubSubClient@^2.8

[env:board_check]
build_src_filter =
 +<board_check.cpp>
 -<main.cpp>
 -<at_passthrough.cpp>
 -<mqtt_smoke.cpp>
 -<adc_sense.cpp>
 -<adc_sense_field.cpp>
 -<adc_sense_wifi.cpp>
 -<gnss_lab.cpp>

[env:tracker]
extra_scripts = pre:scripts/version.py
build_src_filter =
 +<main.cpp>
 -<board_check.cpp>
 -<at_passthrough.cpp>
 -<mqtt_smoke.cpp>
 -<adc_sense.cpp>
 -<adc_sense_field.cpp>
 -<adc_sense_wifi.cpp>
 -<gnss_lab.cpp>

[env:at_passthrough]
build_src_filter =
 +<at_passthrough.cpp>
 -<main.cpp>
 -<board_check.cpp>
 -<mqtt_smoke.cpp>
 -<adc_sense.cpp>
 -<adc_sense_field.cpp>
 -<adc_sense_wifi.cpp>
 -<gnss_lab.cpp>

[env:mqtt_smoke]
build_src_filter =
 +<mqtt_smoke.cpp>
 -<main.cpp>
 -<board_check.cpp>
 -<at_passthrough.cpp>
 -<adc_sense.cpp>
 -<adc_sense_field.cpp>
 -<adc_sense_wifi.cpp>
 -<gnss_lab.cpp>

[env:adc_sense]
build_src_filter =
 +<adc_sense.cpp>
 -<main.cpp>
 -<board_check.cpp>
 -<at_passthrough.cpp>
 -<mqtt_smoke.cpp>
 -<adc_sense_field.cpp>
 -<adc_sense_wifi.cpp>
 -<gnss_lab.cpp>

[env:adc_sense_field]
build_src_filter =
 +<adc_sense_field.cpp>
 -<main.cpp>
 -<board_check.cpp>
 -<at_passthrough.cpp>
 -<mqtt_smoke.cpp>
 -<adc_sense.cpp>
 -<adc_sense_wifi.cpp>
 -<gnss_lab.cpp>

[env:adc_sense_wifi]
build_src_filter =
 +<adc_sense_wifi.cpp>
 -<main.cpp>
 -<board_check.cpp>
 -<at_passthrough.cpp>
 -<mqtt_smoke.cpp>
 -<adc_sense.cpp>
 -<adc_sense_field.cpp>
 -<gnss_lab.cpp>

[env:gnss_lab]
monitor_filters = log2file
build_src_filter =
 +<gnss_lab.cpp>
 -<main.cpp>
 -<board_check.cpp>
 -<at_passthrough.cpp>
 -<mqtt_smoke.cpp>
 -<adc_sense.cpp>
 -<adc_sense_field.cpp>
 -<adc_sense_wifi.cpp>
