[platformio]
default_envs = tracker

[env]
platform = espressif32
board = esp32s3usbotg
framework = arduino
monitor_speed = 115200
upload_port = COM5

build_flags =
 -D ARDUINO_USB_CDC_ON_BOOT=1
 -D ARDUINO_USB_MODE=1

lib_deps =
 https://github.com/lewisxhe/TinyGSM-fork.git
 vshymanskyy/StreamDebugger@^1.0.1
 knolleary/PubSubClient@^2.8

; ; ====== Firmware principal (tracker) ======
; [env:tracker]
; build_src_filter =
; +<*>
; -<at_passthrough.cpp>

; ; ====== Utilidad: AT Passthrough (módem) ======
; [env:at_passthrough]
; build_src_filter =
; +<*>
; -<tracker.cpp>

 ; ====== Prueba segura de placa ======
[env:board_check]
build_src_filter =
 +<board_check.cpp>
 -<main.cpp>
 -<at_passthrough.cpp>
 -<mqtt_smoke.cpp>
 -<adc_sense.cpp>

; ====== Firmware principal ======
[env:tracker]
build_src_filter =
 +<main.cpp>
 -<board_check.cpp>
 -<at_passthrough.cpp>
 -<mqtt_smoke.cpp>
 -<adc_sense.cpp>

; ====== Utilidad: AT Passthrough ======
[env:at_passthrough]
build_src_filter =
 +<at_passthrough.cpp>
 -<main.cpp>
 -<board_check.cpp>
 -<mqtt_smoke.cpp>
 -<adc_sense.cpp>

; ====== Utilidad: Prueba básica de MQTT ======
[env:mqtt_smoke]
build_src_filter =
 +<mqtt_smoke.cpp>
 -<main.cpp>
 -<board_check.cpp>
 -<at_passthrough.cpp>
 -<adc_sense.cpp>

; ====== Utilidad: Lectura ADC del divisor de ignicion (GPIO9) ======
[env:adc_sense]
build_src_filter =
 +<adc_sense.cpp>
 -<main.cpp>
 -<board_check.cpp>
 -<at_passthrough.cpp>
 -<mqtt_smoke.cpp>
